<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHtu1w3S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHtu1w3S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHtu1w3S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHtu1w3S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHtu1w3S\App_KernelDevDebugContainer([
    'container.build_hash' => 'Htu1w3S',
    'container.build_id' => '49706b8c',
    'container.build_time' => 1638891364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHtu1w3S');
